// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: operator/v1/operator/message.proto

package operator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_ACTIVE    State = 0
	State_INACTIVE  State = 1
	State_DEPLOYING State = 2
	State_FAILED    State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
		2: "DEPLOYING",
		3: "FAILED",
	}
	State_value = map[string]int32{
		"ACTIVE":    0,
		"INACTIVE":  1,
		"DEPLOYING": 2,
		"FAILED":    3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_v1_operator_message_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_operator_v1_operator_message_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{0}
}

type OperatorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State         State                  `protobuf:"varint,4,opt,name=state,proto3,enum=operator.v1.operator.State" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorStatus) Reset() {
	*x = OperatorStatus{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorStatus) ProtoMessage() {}

func (x *OperatorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorStatus.ProtoReflect.Descriptor instead.
func (*OperatorStatus) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorStatus) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *OperatorStatus) GetState() State {
	if x != nil {
		return x.State
	}
	return State_ACTIVE
}

func (x *OperatorStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OperatorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	RepoRef       string                 `protobuf:"bytes,3,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorConfig) Reset() {
	*x = OperatorConfig{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorConfig) ProtoMessage() {}

func (x *OperatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorConfig.ProtoReflect.Descriptor instead.
func (*OperatorConfig) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorConfig) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *OperatorConfig) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{2}
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*OperatorStatus      `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"` // returns all revisions of the operator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetRevisions() []*OperatorStatus {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *OperatorConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeResponse) GetConfig() *OperatorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *OperatorConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetConfig() *OperatorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{8}
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_operator_v1_operator_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1_operator_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1_operator_message_proto_rawDescGZIP(), []int{9}
}

var File_operator_v1_operator_message_proto protoreflect.FileDescriptor

const file_operator_v1_operator_message_proto_rawDesc = "" +
	"\n" +
	"\"operator/v1/operator/message.proto\x12\x14operator.v1.operator\"u\n" +
	"\x0eOperatorStatus\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x121\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1b.operator.v1.operator.StateR\x05state\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"F\n" +
	"\x0eOperatorConfig\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12\x19\n" +
	"\brepo_ref\x18\x03 \x01(\tR\arepoRef\"\f\n" +
	"\n" +
	"GetRequest\"Q\n" +
	"\vGetResponse\x12B\n" +
	"\trevisions\x18\x01 \x03(\v2$.operator.v1.operator.OperatorStatusR\trevisions\"-\n" +
	"\x0fDescribeRequest\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\"P\n" +
	"\x10DescribeResponse\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.operator.v1.operator.OperatorConfigR\x06config\"M\n" +
	"\rUpdateRequest\x12<\n" +
	"\x06config\x18\x01 \x01(\v2$.operator.v1.operator.OperatorConfigR\x06config\",\n" +
	"\x0eUpdateResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\"\x10\n" +
	"\x0eDestroyRequest\"\x11\n" +
	"\x0fDestroyResponse*<\n" +
	"\x05State\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\f\n" +
	"\bINACTIVE\x10\x01\x12\r\n" +
	"\tDEPLOYING\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03B7Z5github.com/megakuul/miam/pkg/api/operator/v1/operatorb\x06proto3"

var (
	file_operator_v1_operator_message_proto_rawDescOnce sync.Once
	file_operator_v1_operator_message_proto_rawDescData []byte
)

func file_operator_v1_operator_message_proto_rawDescGZIP() []byte {
	file_operator_v1_operator_message_proto_rawDescOnce.Do(func() {
		file_operator_v1_operator_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operator_v1_operator_message_proto_rawDesc), len(file_operator_v1_operator_message_proto_rawDesc)))
	})
	return file_operator_v1_operator_message_proto_rawDescData
}

var file_operator_v1_operator_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operator_v1_operator_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_operator_v1_operator_message_proto_goTypes = []any{
	(State)(0),               // 0: operator.v1.operator.State
	(*OperatorStatus)(nil),   // 1: operator.v1.operator.OperatorStatus
	(*OperatorConfig)(nil),   // 2: operator.v1.operator.OperatorConfig
	(*GetRequest)(nil),       // 3: operator.v1.operator.GetRequest
	(*GetResponse)(nil),      // 4: operator.v1.operator.GetResponse
	(*DescribeRequest)(nil),  // 5: operator.v1.operator.DescribeRequest
	(*DescribeResponse)(nil), // 6: operator.v1.operator.DescribeResponse
	(*UpdateRequest)(nil),    // 7: operator.v1.operator.UpdateRequest
	(*UpdateResponse)(nil),   // 8: operator.v1.operator.UpdateResponse
	(*DestroyRequest)(nil),   // 9: operator.v1.operator.DestroyRequest
	(*DestroyResponse)(nil),  // 10: operator.v1.operator.DestroyResponse
}
var file_operator_v1_operator_message_proto_depIdxs = []int32{
	0, // 0: operator.v1.operator.OperatorStatus.state:type_name -> operator.v1.operator.State
	1, // 1: operator.v1.operator.GetResponse.revisions:type_name -> operator.v1.operator.OperatorStatus
	2, // 2: operator.v1.operator.DescribeResponse.config:type_name -> operator.v1.operator.OperatorConfig
	2, // 3: operator.v1.operator.UpdateRequest.config:type_name -> operator.v1.operator.OperatorConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_operator_v1_operator_message_proto_init() }
func file_operator_v1_operator_message_proto_init() {
	if File_operator_v1_operator_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_v1_operator_message_proto_rawDesc), len(file_operator_v1_operator_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operator_v1_operator_message_proto_goTypes,
		DependencyIndexes: file_operator_v1_operator_message_proto_depIdxs,
		EnumInfos:         file_operator_v1_operator_message_proto_enumTypes,
		MessageInfos:      file_operator_v1_operator_message_proto_msgTypes,
	}.Build()
	File_operator_v1_operator_message_proto = out.File
	file_operator_v1_operator_message_proto_goTypes = nil
	file_operator_v1_operator_message_proto_depIdxs = nil
}
