// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: operator/v1/operator/service.proto

package operator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_operator_v1_operator_service_proto protoreflect.FileDescriptor

const file_operator_v1_operator_service_proto_rawDesc = "" +
	"\n" +
	"\"operator/v1/operator/service.proto\x12\x14operator.v1.operator\x1a\"operator/v1/operator/message.proto2\xf0\x02\n" +
	"\x12MaintenanceService\x12L\n" +
	"\x03Get\x12 .operator.v1.operator.GetRequest\x1a!.operator.v1.operator.GetResponse\"\x00\x12[\n" +
	"\bDescribe\x12%.operator.v1.operator.DescribeRequest\x1a&.operator.v1.operator.DescribeResponse\"\x00\x12U\n" +
	"\x06Update\x12#.operator.v1.operator.UpdateRequest\x1a$.operator.v1.operator.UpdateResponse\"\x00\x12X\n" +
	"\aDestroy\x12$.operator.v1.operator.DestroyRequest\x1a%.operator.v1.operator.DestroyResponse\"\x00B7Z5github.com/megakuul/miam/pkg/api/operator/v1/operatorb\x06proto3"

var file_operator_v1_operator_service_proto_goTypes = []any{
	(*GetRequest)(nil),       // 0: operator.v1.operator.GetRequest
	(*DescribeRequest)(nil),  // 1: operator.v1.operator.DescribeRequest
	(*UpdateRequest)(nil),    // 2: operator.v1.operator.UpdateRequest
	(*DestroyRequest)(nil),   // 3: operator.v1.operator.DestroyRequest
	(*GetResponse)(nil),      // 4: operator.v1.operator.GetResponse
	(*DescribeResponse)(nil), // 5: operator.v1.operator.DescribeResponse
	(*UpdateResponse)(nil),   // 6: operator.v1.operator.UpdateResponse
	(*DestroyResponse)(nil),  // 7: operator.v1.operator.DestroyResponse
}
var file_operator_v1_operator_service_proto_depIdxs = []int32{
	0, // 0: operator.v1.operator.MaintenanceService.Get:input_type -> operator.v1.operator.GetRequest
	1, // 1: operator.v1.operator.MaintenanceService.Describe:input_type -> operator.v1.operator.DescribeRequest
	2, // 2: operator.v1.operator.MaintenanceService.Update:input_type -> operator.v1.operator.UpdateRequest
	3, // 3: operator.v1.operator.MaintenanceService.Destroy:input_type -> operator.v1.operator.DestroyRequest
	4, // 4: operator.v1.operator.MaintenanceService.Get:output_type -> operator.v1.operator.GetResponse
	5, // 5: operator.v1.operator.MaintenanceService.Describe:output_type -> operator.v1.operator.DescribeResponse
	6, // 6: operator.v1.operator.MaintenanceService.Update:output_type -> operator.v1.operator.UpdateResponse
	7, // 7: operator.v1.operator.MaintenanceService.Destroy:output_type -> operator.v1.operator.DestroyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_operator_v1_operator_service_proto_init() }
func file_operator_v1_operator_service_proto_init() {
	if File_operator_v1_operator_service_proto != nil {
		return
	}
	file_operator_v1_operator_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_v1_operator_service_proto_rawDesc), len(file_operator_v1_operator_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_v1_operator_service_proto_goTypes,
		DependencyIndexes: file_operator_v1_operator_service_proto_depIdxs,
	}.Build()
	File_operator_v1_operator_service_proto = out.File
	file_operator_v1_operator_service_proto_goTypes = nil
	file_operator_v1_operator_service_proto_depIdxs = nil
}
