// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file operator/v1/cluster/message.proto (package operator.v1.cluster, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file operator/v1/cluster/message.proto.
 */
export const file_operator_v1_cluster_message: GenFile = /*@__PURE__*/
  fileDesc("CiFvcGVyYXRvci92MS9jbHVzdGVyL21lc3NhZ2UucHJvdG8SE29wZXJhdG9yLnYxLmNsdXN0ZXIidwoNQ2x1c3RlclN0YXR1cxIMCgRuYW1lGAEgASgJEhAKCHJldmlzaW9uGAIgASgJEgwKBHRhZ3MYAyADKAkSKQoFc3RhdGUYBCABKA4yGi5vcGVyYXRvci52MS5jbHVzdGVyLlN0YXRlEg0KBWVycm9yGAUgASgJIqwBCg1DbHVzdGVyQ29uZmlnEhAKCHJlcG9fdXJsGAIgASgJEhAKCHJlcG9fcmVmGAMgASgJEjsKDmNvbnRyb2xfY29uZmlnGAQgASgLMiMub3BlcmF0b3IudjEuY2x1c3Rlci5JbnN0YW5jZUNvbmZpZxI6Cg13b3JrZXJfY29uZmlnGAUgASgLMiMub3BlcmF0b3IudjEuY2x1c3Rlci5JbnN0YW5jZUNvbmZpZyJECg5JbnN0YW5jZUNvbmZpZxIMCgR0eXBlGAEgASgJEhEKCW1pbl9zY2FsZRgCIAEoAxIRCgltYXhfc2NhbGUYAyABKAMiDQoLTGlzdFJlcXVlc3QiRAoMTGlzdFJlc3BvbnNlEjQKCGNsdXN0ZXJzGAEgAygLMiIub3BlcmF0b3IudjEuY2x1c3Rlci5DbHVzdGVyU3RhdHVzIhoKCkdldFJlcXVlc3QSDAoEbmFtZRgBIAEoCSJECgtHZXRSZXNwb25zZRI1CglyZXZpc2lvbnMYASADKAsyIi5vcGVyYXRvci52MS5jbHVzdGVyLkNsdXN0ZXJTdGF0dXMiMQoPRGVzY3JpYmVSZXF1ZXN0EgwKBG5hbWUYASABKAkSEAoIcmV2aXNpb24YAiABKAkiRgoQRGVzY3JpYmVSZXNwb25zZRIyCgZjb25maWcYASABKAsyIi5vcGVyYXRvci52MS5jbHVzdGVyLkNsdXN0ZXJDb25maWciQwoNVXBkYXRlUmVxdWVzdBIyCgZjb25maWcYASABKAsyIi5vcGVyYXRvci52MS5jbHVzdGVyLkNsdXN0ZXJDb25maWciIgoOVXBkYXRlUmVzcG9uc2USEAoIcmV2aXNpb24YASABKAkiHgoORGVzdHJveVJlcXVlc3QSDAoEbmFtZRgBIAEoCSIRCg9EZXN0cm95UmVzcG9uc2UqPAoFU3RhdGUSCgoGQUNUSVZFEAASDAoISU5BQ1RJVkUQARINCglERVBMT1lJTkcQAhIKCgZGQUlMRUQQA0I2WjRnaXRodWIuY29tL21lZ2FrdXVsL21pYW0vcGtnL2FwaS9vcGVyYXRvci92MS9jbHVzdGVyYgZwcm90bzM");

/**
 * @generated from message operator.v1.cluster.ClusterStatus
 */
export type ClusterStatus = Message<"operator.v1.cluster.ClusterStatus"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string revision = 2;
   */
  revision: string;

  /**
   * @generated from field: repeated string tags = 3;
   */
  tags: string[];

  /**
   * @generated from field: operator.v1.cluster.State state = 4;
   */
  state: State;

  /**
   * @generated from field: string error = 5;
   */
  error: string;
};

/**
 * Describes the message operator.v1.cluster.ClusterStatus.
 * Use `create(ClusterStatusSchema)` to create a new message.
 */
export const ClusterStatusSchema: GenMessage<ClusterStatus> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 0);

/**
 * @generated from message operator.v1.cluster.ClusterConfig
 */
export type ClusterConfig = Message<"operator.v1.cluster.ClusterConfig"> & {
  /**
   * @generated from field: string repo_url = 2;
   */
  repoUrl: string;

  /**
   * @generated from field: string repo_ref = 3;
   */
  repoRef: string;

  /**
   * @generated from field: operator.v1.cluster.InstanceConfig control_config = 4;
   */
  controlConfig?: InstanceConfig;

  /**
   * @generated from field: operator.v1.cluster.InstanceConfig worker_config = 5;
   */
  workerConfig?: InstanceConfig;
};

/**
 * Describes the message operator.v1.cluster.ClusterConfig.
 * Use `create(ClusterConfigSchema)` to create a new message.
 */
export const ClusterConfigSchema: GenMessage<ClusterConfig> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 1);

/**
 * @generated from message operator.v1.cluster.InstanceConfig
 */
export type InstanceConfig = Message<"operator.v1.cluster.InstanceConfig"> & {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * @generated from field: int64 min_scale = 2;
   */
  minScale: bigint;

  /**
   * @generated from field: int64 max_scale = 3;
   */
  maxScale: bigint;
};

/**
 * Describes the message operator.v1.cluster.InstanceConfig.
 * Use `create(InstanceConfigSchema)` to create a new message.
 */
export const InstanceConfigSchema: GenMessage<InstanceConfig> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 2);

/**
 * @generated from message operator.v1.cluster.ListRequest
 */
export type ListRequest = Message<"operator.v1.cluster.ListRequest"> & {
};

/**
 * Describes the message operator.v1.cluster.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 3);

/**
 * @generated from message operator.v1.cluster.ListResponse
 */
export type ListResponse = Message<"operator.v1.cluster.ListResponse"> & {
  /**
   * returns latest revision of all clusters
   *
   * @generated from field: repeated operator.v1.cluster.ClusterStatus clusters = 1;
   */
  clusters: ClusterStatus[];
};

/**
 * Describes the message operator.v1.cluster.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 4);

/**
 * @generated from message operator.v1.cluster.GetRequest
 */
export type GetRequest = Message<"operator.v1.cluster.GetRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message operator.v1.cluster.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 5);

/**
 * @generated from message operator.v1.cluster.GetResponse
 */
export type GetResponse = Message<"operator.v1.cluster.GetResponse"> & {
  /**
   * returns all revisions of one cluster 
   *
   * @generated from field: repeated operator.v1.cluster.ClusterStatus revisions = 1;
   */
  revisions: ClusterStatus[];
};

/**
 * Describes the message operator.v1.cluster.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 6);

/**
 * @generated from message operator.v1.cluster.DescribeRequest
 */
export type DescribeRequest = Message<"operator.v1.cluster.DescribeRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string revision = 2;
   */
  revision: string;
};

/**
 * Describes the message operator.v1.cluster.DescribeRequest.
 * Use `create(DescribeRequestSchema)` to create a new message.
 */
export const DescribeRequestSchema: GenMessage<DescribeRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 7);

/**
 * @generated from message operator.v1.cluster.DescribeResponse
 */
export type DescribeResponse = Message<"operator.v1.cluster.DescribeResponse"> & {
  /**
   * @generated from field: operator.v1.cluster.ClusterConfig config = 1;
   */
  config?: ClusterConfig;
};

/**
 * Describes the message operator.v1.cluster.DescribeResponse.
 * Use `create(DescribeResponseSchema)` to create a new message.
 */
export const DescribeResponseSchema: GenMessage<DescribeResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 8);

/**
 * @generated from message operator.v1.cluster.UpdateRequest
 */
export type UpdateRequest = Message<"operator.v1.cluster.UpdateRequest"> & {
  /**
   * @generated from field: operator.v1.cluster.ClusterConfig config = 1;
   */
  config?: ClusterConfig;
};

/**
 * Describes the message operator.v1.cluster.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 9);

/**
 * @generated from message operator.v1.cluster.UpdateResponse
 */
export type UpdateResponse = Message<"operator.v1.cluster.UpdateResponse"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;
};

/**
 * Describes the message operator.v1.cluster.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 10);

/**
 * @generated from message operator.v1.cluster.DestroyRequest
 */
export type DestroyRequest = Message<"operator.v1.cluster.DestroyRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message operator.v1.cluster.DestroyRequest.
 * Use `create(DestroyRequestSchema)` to create a new message.
 */
export const DestroyRequestSchema: GenMessage<DestroyRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 11);

/**
 * @generated from message operator.v1.cluster.DestroyResponse
 */
export type DestroyResponse = Message<"operator.v1.cluster.DestroyResponse"> & {
};

/**
 * Describes the message operator.v1.cluster.DestroyResponse.
 * Use `create(DestroyResponseSchema)` to create a new message.
 */
export const DestroyResponseSchema: GenMessage<DestroyResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_cluster_message, 12);

/**
 * @generated from enum operator.v1.cluster.State
 */
export enum State {
  /**
   * @generated from enum value: ACTIVE = 0;
   */
  ACTIVE = 0,

  /**
   * @generated from enum value: INACTIVE = 1;
   */
  INACTIVE = 1,

  /**
   * @generated from enum value: DEPLOYING = 2;
   */
  DEPLOYING = 2,

  /**
   * @generated from enum value: FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum operator.v1.cluster.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_operator_v1_cluster_message, 0);

