// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file operator/v1/cluster/service.proto (package operator.v1.cluster, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { DescribeRequestSchema, DescribeResponseSchema, DestroyRequestSchema, DestroyResponseSchema, GetRequestSchema, GetResponseSchema, ListRequestSchema, ListResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_operator_v1_cluster_message } from "./message_pb";

/**
 * Describes the file operator/v1/cluster/service.proto.
 */
export const file_operator_v1_cluster_service: GenFile = /*@__PURE__*/
  fileDesc("CiFvcGVyYXRvci92MS9jbHVzdGVyL3NlcnZpY2UucHJvdG8SE29wZXJhdG9yLnYxLmNsdXN0ZXIyswMKDkNsdXN0ZXJTZXJ2aWNlEk0KBExpc3QSIC5vcGVyYXRvci52MS5jbHVzdGVyLkxpc3RSZXF1ZXN0GiEub3BlcmF0b3IudjEuY2x1c3Rlci5MaXN0UmVzcG9uc2UiABJKCgNHZXQSHy5vcGVyYXRvci52MS5jbHVzdGVyLkdldFJlcXVlc3QaIC5vcGVyYXRvci52MS5jbHVzdGVyLkdldFJlc3BvbnNlIgASWQoIRGVzY3JpYmUSJC5vcGVyYXRvci52MS5jbHVzdGVyLkRlc2NyaWJlUmVxdWVzdBolLm9wZXJhdG9yLnYxLmNsdXN0ZXIuRGVzY3JpYmVSZXNwb25zZSIAElMKBlVwZGF0ZRIiLm9wZXJhdG9yLnYxLmNsdXN0ZXIuVXBkYXRlUmVxdWVzdBojLm9wZXJhdG9yLnYxLmNsdXN0ZXIuVXBkYXRlUmVzcG9uc2UiABJWCgdEZXN0cm95EiMub3BlcmF0b3IudjEuY2x1c3Rlci5EZXN0cm95UmVxdWVzdBokLm9wZXJhdG9yLnYxLmNsdXN0ZXIuRGVzdHJveVJlc3BvbnNlIgBCNlo0Z2l0aHViLmNvbS9tZWdha3V1bC9taWFtL3BrZy9hcGkvb3BlcmF0b3IvdjEvY2x1c3RlcmIGcHJvdG8z", [file_operator_v1_cluster_message]);

/**
 * @generated from service operator.v1.cluster.ClusterService
 */
export const ClusterService: GenService<{
  /**
   * @generated from rpc operator.v1.cluster.ClusterService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.cluster.ClusterService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.cluster.ClusterService.Describe
   */
  describe: {
    methodKind: "unary";
    input: typeof DescribeRequestSchema;
    output: typeof DescribeResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.cluster.ClusterService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.cluster.ClusterService.Destroy
   */
  destroy: {
    methodKind: "unary";
    input: typeof DestroyRequestSchema;
    output: typeof DestroyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_operator_v1_cluster_service, 0);

