// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: operator/v1/cluster/service.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_operator_v1_cluster_service_proto protoreflect.FileDescriptor

const file_operator_v1_cluster_service_proto_rawDesc = "" +
	"\n" +
	"!operator/v1/cluster/service.proto\x12\x13operator.v1.cluster\x1a!operator/v1/cluster/message.proto2\xb3\x03\n" +
	"\x0eClusterService\x12M\n" +
	"\x04List\x12 .operator.v1.cluster.ListRequest\x1a!.operator.v1.cluster.ListResponse\"\x00\x12J\n" +
	"\x03Get\x12\x1f.operator.v1.cluster.GetRequest\x1a .operator.v1.cluster.GetResponse\"\x00\x12Y\n" +
	"\bDescribe\x12$.operator.v1.cluster.DescribeRequest\x1a%.operator.v1.cluster.DescribeResponse\"\x00\x12S\n" +
	"\x06Update\x12\".operator.v1.cluster.UpdateRequest\x1a#.operator.v1.cluster.UpdateResponse\"\x00\x12V\n" +
	"\aDestroy\x12#.operator.v1.cluster.DestroyRequest\x1a$.operator.v1.cluster.DestroyResponse\"\x00B6Z4github.com/megakuul/miam/pkg/api/operator/v1/clusterb\x06proto3"

var file_operator_v1_cluster_service_proto_goTypes = []any{
	(*ListRequest)(nil),      // 0: operator.v1.cluster.ListRequest
	(*GetRequest)(nil),       // 1: operator.v1.cluster.GetRequest
	(*DescribeRequest)(nil),  // 2: operator.v1.cluster.DescribeRequest
	(*UpdateRequest)(nil),    // 3: operator.v1.cluster.UpdateRequest
	(*DestroyRequest)(nil),   // 4: operator.v1.cluster.DestroyRequest
	(*ListResponse)(nil),     // 5: operator.v1.cluster.ListResponse
	(*GetResponse)(nil),      // 6: operator.v1.cluster.GetResponse
	(*DescribeResponse)(nil), // 7: operator.v1.cluster.DescribeResponse
	(*UpdateResponse)(nil),   // 8: operator.v1.cluster.UpdateResponse
	(*DestroyResponse)(nil),  // 9: operator.v1.cluster.DestroyResponse
}
var file_operator_v1_cluster_service_proto_depIdxs = []int32{
	0, // 0: operator.v1.cluster.ClusterService.List:input_type -> operator.v1.cluster.ListRequest
	1, // 1: operator.v1.cluster.ClusterService.Get:input_type -> operator.v1.cluster.GetRequest
	2, // 2: operator.v1.cluster.ClusterService.Describe:input_type -> operator.v1.cluster.DescribeRequest
	3, // 3: operator.v1.cluster.ClusterService.Update:input_type -> operator.v1.cluster.UpdateRequest
	4, // 4: operator.v1.cluster.ClusterService.Destroy:input_type -> operator.v1.cluster.DestroyRequest
	5, // 5: operator.v1.cluster.ClusterService.List:output_type -> operator.v1.cluster.ListResponse
	6, // 6: operator.v1.cluster.ClusterService.Get:output_type -> operator.v1.cluster.GetResponse
	7, // 7: operator.v1.cluster.ClusterService.Describe:output_type -> operator.v1.cluster.DescribeResponse
	8, // 8: operator.v1.cluster.ClusterService.Update:output_type -> operator.v1.cluster.UpdateResponse
	9, // 9: operator.v1.cluster.ClusterService.Destroy:output_type -> operator.v1.cluster.DestroyResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_operator_v1_cluster_service_proto_init() }
func file_operator_v1_cluster_service_proto_init() {
	if File_operator_v1_cluster_service_proto != nil {
		return
	}
	file_operator_v1_cluster_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_v1_cluster_service_proto_rawDesc), len(file_operator_v1_cluster_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_v1_cluster_service_proto_goTypes,
		DependencyIndexes: file_operator_v1_cluster_service_proto_depIdxs,
	}.Build()
	File_operator_v1_cluster_service_proto = out.File
	file_operator_v1_cluster_service_proto_goTypes = nil
	file_operator_v1_cluster_service_proto_depIdxs = nil
}
