// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file operator/v1/operator/message.proto (package operator.v1.operator, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file operator/v1/operator/message.proto.
 */
export const file_operator_v1_operator_message: GenFile = /*@__PURE__*/
  fileDesc("CiJvcGVyYXRvci92MS9vcGVyYXRvci9tZXNzYWdlLnByb3RvEhRvcGVyYXRvci52MS5vcGVyYXRvciJdCg5PcGVyYXRvclN0YXR1cxIQCghyZXZpc2lvbhgCIAEoCRIqCgVzdGF0ZRgEIAEoDjIbLm9wZXJhdG9yLnYxLm9wZXJhdG9yLlN0YXRlEg0KBWVycm9yGAUgASgJIjQKDk9wZXJhdG9yQ29uZmlnEhAKCHJlcG9fdXJsGAIgASgJEhAKCHJlcG9fcmVmGAMgASgJIgwKCkdldFJlcXVlc3QiRgoLR2V0UmVzcG9uc2USNwoJcmV2aXNpb25zGAEgAygLMiQub3BlcmF0b3IudjEub3BlcmF0b3IuT3BlcmF0b3JTdGF0dXMiIwoPRGVzY3JpYmVSZXF1ZXN0EhAKCHJldmlzaW9uGAEgASgJIkgKEERlc2NyaWJlUmVzcG9uc2USNAoGY29uZmlnGAEgASgLMiQub3BlcmF0b3IudjEub3BlcmF0b3IuT3BlcmF0b3JDb25maWciRQoNVXBkYXRlUmVxdWVzdBI0CgZjb25maWcYASABKAsyJC5vcGVyYXRvci52MS5vcGVyYXRvci5PcGVyYXRvckNvbmZpZyIiCg5VcGRhdGVSZXNwb25zZRIQCghyZXZpc2lvbhgBIAEoCSIQCg5EZXN0cm95UmVxdWVzdCIRCg9EZXN0cm95UmVzcG9uc2UqPAoFU3RhdGUSCgoGQUNUSVZFEAASDAoISU5BQ1RJVkUQARINCglERVBMT1lJTkcQAhIKCgZGQUlMRUQQA0I3WjVnaXRodWIuY29tL21lZ2FrdXVsL21pYW0vcGtnL2FwaS9vcGVyYXRvci92MS9vcGVyYXRvcmIGcHJvdG8z");

/**
 * @generated from message operator.v1.operator.OperatorStatus
 */
export type OperatorStatus = Message<"operator.v1.operator.OperatorStatus"> & {
  /**
   * @generated from field: string revision = 2;
   */
  revision: string;

  /**
   * @generated from field: operator.v1.operator.State state = 4;
   */
  state: State;

  /**
   * @generated from field: string error = 5;
   */
  error: string;
};

/**
 * Describes the message operator.v1.operator.OperatorStatus.
 * Use `create(OperatorStatusSchema)` to create a new message.
 */
export const OperatorStatusSchema: GenMessage<OperatorStatus> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 0);

/**
 * @generated from message operator.v1.operator.OperatorConfig
 */
export type OperatorConfig = Message<"operator.v1.operator.OperatorConfig"> & {
  /**
   * @generated from field: string repo_url = 2;
   */
  repoUrl: string;

  /**
   * @generated from field: string repo_ref = 3;
   */
  repoRef: string;
};

/**
 * Describes the message operator.v1.operator.OperatorConfig.
 * Use `create(OperatorConfigSchema)` to create a new message.
 */
export const OperatorConfigSchema: GenMessage<OperatorConfig> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 1);

/**
 * @generated from message operator.v1.operator.GetRequest
 */
export type GetRequest = Message<"operator.v1.operator.GetRequest"> & {
};

/**
 * Describes the message operator.v1.operator.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 2);

/**
 * @generated from message operator.v1.operator.GetResponse
 */
export type GetResponse = Message<"operator.v1.operator.GetResponse"> & {
  /**
   * returns all revisions of the operator 
   *
   * @generated from field: repeated operator.v1.operator.OperatorStatus revisions = 1;
   */
  revisions: OperatorStatus[];
};

/**
 * Describes the message operator.v1.operator.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 3);

/**
 * @generated from message operator.v1.operator.DescribeRequest
 */
export type DescribeRequest = Message<"operator.v1.operator.DescribeRequest"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;
};

/**
 * Describes the message operator.v1.operator.DescribeRequest.
 * Use `create(DescribeRequestSchema)` to create a new message.
 */
export const DescribeRequestSchema: GenMessage<DescribeRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 4);

/**
 * @generated from message operator.v1.operator.DescribeResponse
 */
export type DescribeResponse = Message<"operator.v1.operator.DescribeResponse"> & {
  /**
   * @generated from field: operator.v1.operator.OperatorConfig config = 1;
   */
  config?: OperatorConfig;
};

/**
 * Describes the message operator.v1.operator.DescribeResponse.
 * Use `create(DescribeResponseSchema)` to create a new message.
 */
export const DescribeResponseSchema: GenMessage<DescribeResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 5);

/**
 * @generated from message operator.v1.operator.UpdateRequest
 */
export type UpdateRequest = Message<"operator.v1.operator.UpdateRequest"> & {
  /**
   * @generated from field: operator.v1.operator.OperatorConfig config = 1;
   */
  config?: OperatorConfig;
};

/**
 * Describes the message operator.v1.operator.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 6);

/**
 * @generated from message operator.v1.operator.UpdateResponse
 */
export type UpdateResponse = Message<"operator.v1.operator.UpdateResponse"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;
};

/**
 * Describes the message operator.v1.operator.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 7);

/**
 * @generated from message operator.v1.operator.DestroyRequest
 */
export type DestroyRequest = Message<"operator.v1.operator.DestroyRequest"> & {
};

/**
 * Describes the message operator.v1.operator.DestroyRequest.
 * Use `create(DestroyRequestSchema)` to create a new message.
 */
export const DestroyRequestSchema: GenMessage<DestroyRequest> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 8);

/**
 * @generated from message operator.v1.operator.DestroyResponse
 */
export type DestroyResponse = Message<"operator.v1.operator.DestroyResponse"> & {
};

/**
 * Describes the message operator.v1.operator.DestroyResponse.
 * Use `create(DestroyResponseSchema)` to create a new message.
 */
export const DestroyResponseSchema: GenMessage<DestroyResponse> = /*@__PURE__*/
  messageDesc(file_operator_v1_operator_message, 9);

/**
 * @generated from enum operator.v1.operator.State
 */
export enum State {
  /**
   * @generated from enum value: ACTIVE = 0;
   */
  ACTIVE = 0,

  /**
   * @generated from enum value: INACTIVE = 1;
   */
  INACTIVE = 1,

  /**
   * @generated from enum value: DEPLOYING = 2;
   */
  DEPLOYING = 2,

  /**
   * @generated from enum value: FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum operator.v1.operator.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_operator_v1_operator_message, 0);

