// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file operator/v1/operator/service.proto (package operator.v1.operator, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { DescribeRequestSchema, DescribeResponseSchema, DestroyRequestSchema, DestroyResponseSchema, GetRequestSchema, GetResponseSchema, UpdateRequestSchema, UpdateResponseSchema } from "./message_pb";
import { file_operator_v1_operator_message } from "./message_pb";

/**
 * Describes the file operator/v1/operator/service.proto.
 */
export const file_operator_v1_operator_service: GenFile = /*@__PURE__*/
  fileDesc("CiJvcGVyYXRvci92MS9vcGVyYXRvci9zZXJ2aWNlLnByb3RvEhRvcGVyYXRvci52MS5vcGVyYXRvcjLwAgoSTWFpbnRlbmFuY2VTZXJ2aWNlEkwKA0dldBIgLm9wZXJhdG9yLnYxLm9wZXJhdG9yLkdldFJlcXVlc3QaIS5vcGVyYXRvci52MS5vcGVyYXRvci5HZXRSZXNwb25zZSIAElsKCERlc2NyaWJlEiUub3BlcmF0b3IudjEub3BlcmF0b3IuRGVzY3JpYmVSZXF1ZXN0GiYub3BlcmF0b3IudjEub3BlcmF0b3IuRGVzY3JpYmVSZXNwb25zZSIAElUKBlVwZGF0ZRIjLm9wZXJhdG9yLnYxLm9wZXJhdG9yLlVwZGF0ZVJlcXVlc3QaJC5vcGVyYXRvci52MS5vcGVyYXRvci5VcGRhdGVSZXNwb25zZSIAElgKB0Rlc3Ryb3kSJC5vcGVyYXRvci52MS5vcGVyYXRvci5EZXN0cm95UmVxdWVzdBolLm9wZXJhdG9yLnYxLm9wZXJhdG9yLkRlc3Ryb3lSZXNwb25zZSIAQjdaNWdpdGh1Yi5jb20vbWVnYWt1dWwvbWlhbS9wa2cvYXBpL29wZXJhdG9yL3YxL29wZXJhdG9yYgZwcm90bzM", [file_operator_v1_operator_message]);

/**
 * @generated from service operator.v1.operator.MaintenanceService
 */
export const MaintenanceService: GenService<{
  /**
   * @generated from rpc operator.v1.operator.MaintenanceService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetRequestSchema;
    output: typeof GetResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.operator.MaintenanceService.Describe
   */
  describe: {
    methodKind: "unary";
    input: typeof DescribeRequestSchema;
    output: typeof DescribeResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.operator.MaintenanceService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc operator.v1.operator.MaintenanceService.Destroy
   */
  destroy: {
    methodKind: "unary";
    input: typeof DestroyRequestSchema;
    output: typeof DestroyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_operator_v1_operator_service, 0);

